"""
Notification Builder

Builds clean alert messages from AI-generated pipeline incident summaries.
These messages can be sent to Slack, email, ticketing systems, or dashboards.
"""

from typing import Any, Dict


def build_notification(summary: Dict[str, Any]) -> str:
    """
    Build a readable incident notification message.

    Args:
        summary: Incident summary generated by the pipeline analysis agent.

    Returns:
        Formatted notification message.
    """

    downstream_impact = summary.get("downstream_impact") or ["No downstream impact identified"]

    message = f"""
Data Pipeline Alert

Pipeline: {summary.get("pipeline_name")}
Environment: {summary.get("environment")}
Status: {summary.get("status")}
Failed Task: {summary.get("failed_task")}

Likely Cause:
{summary.get("likely_cause")}

Downstream Impact:
{", ".join(downstream_impact)}

Recommended Action:
{summary.get("recommended_action")}

Priority:
{summary.get("priority")}
""".strip()

    return message


if __name__ == "__main__":
    sample_summary = {
        "pipeline_name": "customer_activity_daily_load",
        "environment": "production",
        "status": "failed",
        "failed_task": "validate_schema",
        "likely_cause": "Schema change detected in source data",
        "downstream_impact": ["Executive Activity Dashboard"],
        "recommended_action": "Review source schema and update mapping if approved.",
        "priority": "High",
    }

    print(build_notification(sample_summary))

